/* Reviewed Hungarian quiz bank: 10 categories, 10 questions per category. */
(() => {
  const categories = {
    status: {
      label: "Jelenlegi helyzet",
      questions: [
        ["A Chat Control 1.0 2026. április 3-án lejárt.", true, "Az ideiglenes kivétel ezen a napon hatályát vesztette. A visszaállításáról 2026. július 14-én még nem született végleges döntés."],
        ["A Chat Control 2.0 2026. július 14-én már hatályos uniós rendelet.", false, "A 2.0 továbbra is rendes jogalkotási eljárásban tárgyalt rendelettervezet. A Parlament és a Tanács álláspontja még nem vált közös, végleges jogszabállyá."],
        ["Az 1.0 és a 2.0 két külön jogalkotási történet.", true, "Az 1.0 egy ideiglenes ePrivacy-kivétel volt. A 2.0 egy állandó megelőzési, felderítési, bejelentési és eltávolítási keretet létrehozó javaslat."],
        ["Jelenleg minden uniós üzenetküldő köteles minden üzenetet átvizsgálni.", false, "Nincs hatályos, állandó, minden szolgáltatót általános vizsgálatra kötelező uniós szabály. Ettől még a tervezett technikai képességek és jogi irány komoly vitát indokolnak."],
        ["A 2026. júliusi parlamenti döntés után a Tanácsnak még reagálnia kell a módosításokra.", true, "A Parlament módosította a Tanács ideiglenes visszaállítási szövegét. A szöveg csak további intézményi lépések után válhat jogszabállyá."],
        ["A 2026. július 9-i szavazás végleg lezárta a Chat Control 2.0 ügyét.", false, "A július 9-i vita az ideiglenes kivétel visszaállításáról szólt. A tartós 2.0 javaslat külön eljárásban, trilógusban maradt."],
        ["A jogi helyzet pontos leírása erősíti a kritikus érvelést.", true, "A valótlan „már mindent olvasnak” állítás könnyen cáfolható. A pontos kritika a tervezett képesség, a garanciák és az alapjogi következmények vizsgálatára összpontosít."],
        ["Mivel az 1.0 lejárt, semmilyen további uniós döntés nem hozhatja vissza.", false, "A jogalkotók új rendelettel vagy módosítással ismét létrehozhatnak ideiglenes jogalapot. Ehhez azonban a szükséges intézményi eljárást végig kell vinni."],
        ["A 2.0 pontos kimenetele nyitott, mert még nincs végleges közös szöveg.", true, "A Bizottság, a Parlament és a Tanács kiinduló álláspontjai több fontos ponton eltérnek. A végleges szabály csak az egyeztetés eredményéből derül ki."],
        ["Az „önkéntes felismerés” azt jelenti, hogy minden felhasználó külön engedélyt ad az ellenőrzéshez.", false, "Az önkéntesség az 1.0-ban a szolgáltató döntésére utalt. Az egyes felhasználó nem feltétlenül választhatta meg, hogy a szolgáltatás alkalmaz-e felismerést."],
      ],
    },
    one: {
      label: "Chat Control 1.0",
      questions: [
        ["A 2021/1232 rendelet ideiglenes kivételt adott bizonyos ePrivacy-szabályok alól.", true, "A kivétel lehetővé tette egyes szolgáltatók számára, hogy meghatározott feltételekkel önként folytassák a felismerést. Nem állandó, általános kötelezettségként született."],
        ["A Chat Control 1.0 kötelező felderítési végzéseket vezetett be minden szolgáltatónál.", false, "Az 1.0 szolgáltatói lehetőséget teremtett, nem általános felderítési kötelezettséget. A felderítési végzés a 2.0 javaslatának egyik eleme."],
        ["Az 1.0 hatálya ismert és új bántalmazási anyagokra is kiterjedhetett.", true, "A rendelet nem csak pontosan ismert fájlok felismerését említette. Bizonyos feltételekkel új anyagok és behálózásra utaló kommunikáció felismerésére is lehetőséget adott."],
        ["Az 1.0 kizárólag nyilvános közösségi bejegyzésekre vonatkozott.", false, "Az ideiglenes kivétel személyközi kommunikációs szolgáltatásokat érintett. Éppen a magánkommunikáció titkosságával való ütközés miatt volt szükség külön jogalapra."],
        ["Az 1.0 alkalmazása során a szolgáltatónak adatvédelmi feltételeket is teljesítenie kellett.", true, "A kivétel nem korlátlan felhatalmazás volt. A rendelet technológiai, adatkezelési és jelentési feltételeket is meghatározott."],
        ["A 2024-es módosítás véglegessé tette az 1.0 szabályait.", false, "A 2024/1307 rendelet időben meghosszabbította az átmeneti kivételt. Ettől az még ideiglenes szabály maradt, amely 2026. április 3-án lejárt."],
        ["A szolgáltató önkéntes döntése is érintheti valamennyi felhasználójának magánéletét.", true, "Ha egy szolgáltatás általánosan bekapcsol egy felismerő rendszert, az nemcsak azokra hat, akik külön kérik. Ezért a „szolgáltatói önkéntesség” és a „felhasználói beleegyezés” nem ugyanaz."],
        ["Az 1.0 lejárta automatikusan hatályba léptette a 2.0-t.", false, "A két jogszabály nem váltja automatikusan egymást. A 2.0 csak akkor léphet hatályba, ha a jogalkotók elfogadnak és kihirdetnek egy végleges rendeletet."],
        ["Az 1.0 jogi történetét a 2021-es és a 2024-es rendelet együtt mutatja meg.", true, "A 2021-es rendelet hozta létre a kivételt, a 2024-es pedig meghosszabbította. A jelenlegi állapot megértéséhez mindkét szöveg és a 2026-os fejlemények is szükségesek."],
        ["Az 1.0 alapján a rendőrség közvetlenül, bírósági vagy szolgáltatói lépés nélkül olvasta az összes üzenetet.", false, "A rendszer szolgáltatói felismerésre és találatok bejelentésére épült, nem közvetlen rendőrségi hozzáférésre minden üzenethez. A kritika ettől még vonatkozhat a tömeges vizsgálat és a továbbítás kockázatára."],
      ],
    },
    two: {
      label: "Chat Control 2.0",
      questions: [
        ["A Bizottság 2022-es javaslata állandó megelőzési és felderítési keretet hozna létre.", true, "A tervezet kockázatértékelést, kockázatcsökkentést, felderítést, bejelentést, eltávolítást és új uniós központot is tartalmazott. Ez jóval szélesebb szerkezet az ideiglenes kivételnél."],
        ["A 2.0 kizárólag már ismert tiltott fájlok pontos másolatainak kereséséről szól.", false, "A bizottsági javaslat új anyagok és gyermekek szexuális célú behálózására utaló kommunikáció felismerését is felvetette. Ezek technikailag jóval bizonytalanabb feladatok."],
        ["A 2.0 javaslatában a kockázatértékelés megelőzi az esetleges felderítési végzést.", true, "A tervezett rendszer lépcsőzetes: kockázatértékelés és -csökkentés után kerülhet szóba hatósági intézkedés. A vita egyik kérdése, hogy ezek a lépcsők mennyire korlátozzák ténylegesen a vizsgálatot."],
        ["A Bizottság, a Parlament és a Tanács minden technikai részletben azonos álláspontot képvisel.", false, "A három intézmény álláspontja több ponton eltér, különösen a titkosított kommunikáció, az új tartalom és a behálózás felismerése körül. Éppen ezért folyik intézményközi egyeztetés."],
        ["A felderítési végzés jogi kötelezettséget róhatna egy szolgáltatóra.", true, "A végzés nem egyszerű ajánlás lenne. A pontos cél, hatókör, technológia és jogorvoslat ezért alapvető jelentőségű."],
        ["A 2.0 elfogadásához elég, ha a Bizottság változtatás nélkül újra közzéteszi a javaslatát.", false, "Az uniós rendes jogalkotási eljárásban a Parlamentnek és a Tanácsnak is el kell fogadnia ugyanazt a végleges szöveget. A Bizottság kezdeményez, de nem dönt egyedül."],
        ["A 2.0 gyermekbarát alapbeállításokat és jobb bejelentési folyamatokat is tartalmazhat.", true, "A javaslat nem kizárólag felismerésből áll. Megelőzési, kockázatcsökkentési és áldozatsegítő elemei is vannak, amelyeket külön kell értékelni."],
        ["Ha a jogszöveg kimondja, hogy nem gyengíti a titkosítást, minden technikai megoldás automatikusan biztonságos lesz.", false, "A jogi kijelentés önmagában nem oldja fel a technikai ellentmondást. A készüléken vagy szerveren végzett tartalomvizsgálat működését és támadási felületét konkrétan kell elemezni."],
        ["A 2.0-ról szóló vita az eszköz arányosságáról is szól, nem csak a cél fontosságáról.", true, "A gyermekek védelme legitim és sürgető cél. Az alapjogi teszt azt is vizsgálja, hogy a választott intézkedés szükséges, alkalmas és arányos-e."],
        ["A végleges 2.0 szöveg már biztosan változatlanul tartalmazza a Bizottság 2022-es összes elemét.", false, "A javaslat a jogalkotás során módosulhat, és már most eltérő intézményi álláspontok léteznek. A kiinduló javaslatot nem szabad a végleges eredményként bemutatni."],
      ],
    },
    institutions: {
      label: "Uniós intézmények",
      questions: [
        ["Az Európai Bizottság készítette a 2022-es kiinduló javaslatot.", true, "A Bizottság jogalkotási javaslatot tett. A Parlament és a Tanács ezt követően alakítja ki a saját álláspontját."],
        ["Az Európai Parlament a 27 tagállami kormány minisztereiből áll.", false, "A Parlament közvetlenül választott képviselőkből áll. A tagállami kormányokat az Európai Unió Tanácsában ülő miniszterek képviselik."],
        ["A Parlament és a Tanács ugyanannak a végleges szövegnek az elfogadásával alkothat rendeletet.", true, "A rendes jogalkotási eljárásban mindkét társjogalkotónak egyet kell értenie. Ha az álláspontok eltérnek, további egyeztetésre van szükség."],
        ["A LIBE bizottság 2023-as szavazása a teljes Parlament végleges 2.0-szavazása volt.", false, "A LIBE szakbizottsági álláspontot fogadott el és tárgyalási felhatalmazást készített elő. Ez nem azonos a teljes Parlament végső jogalkotási szavazásával."],
        ["A trilógus a Parlament, a Tanács és a Bizottság közötti intézményközi egyeztetés.", true, "A trilógusban a társjogalkotók kompromisszumos szöveget keresnek, a Bizottság részvételével. Az eredményt később hivatalosan is jóvá kell hagyni."],
        ["Az Európai Unió Tanácsa és az Európai Tanács mindig ugyanazt a feladatot végzi.", false, "Az Európai Unió Tanácsa miniszteri formációkban társjogalkotó. Az Európai Tanács az állam- és kormányfők stratégiai iránymutató intézménye."],
        ["A parlamenti név szerinti szavazásból megállapítható, melyik képviselő hogyan voksolt.", true, "A név szerinti jegyzőkönyv álláspontonként felsorolja a képviselőket. A számok jelentését mindig az adott szavazási kérdéssel együtt kell olvasni."],
        ["Egy tanácsi sajtóközlemény önmagában bizonyítja, hogy a rendelet már hatályba lépett.", false, "A sajtóközlemény intézményi álláspontot vagy politikai megállapodást ismertethet. A hatálybalépéshez elfogadott, kihirdetett jogszabály és a benne szereplő időpont szükséges."],
        ["A magyar állampolgárok az európai parlamenti képviselőket közvetlenül választják.", true, "Magyarországon az európai parlamenti választáson zárt pártlistákra szavaznak; a mandátumokat az így leadott szavazatok alapján osztják ki. A Tanács tagjai ezzel szemben a tagállami kormányok miniszterei."],
        ["Ha a Parlament többsége támogat valamit, a Tanács álláspontja többé nem számít.", false, "A két intézmény társjogalkotó. Egyikük támogatása önmagában nem elég egy rendes eljárásban tárgyalt rendelet elfogadásához."],
      ],
    },
    encryption: {
      label: "Titkosítás",
      questions: [
        ["A végpontok közötti titkosításnál a szolgáltató rendszerint nem kapja meg az üzenet feloldásához szükséges kulcsot.", true, "A tartalmat a küldő eszköze titkosítja, és a címzett eszköze oldja fel. A szolgáltató továbbíthatja az adatot anélkül, hogy a tiszta tartalmat látná."],
        ["A titkosított adatátvitel azt is garantálja, hogy a küldő telefonján semmilyen program nem vizsgálja meg az üzenetet.", false, "Az adatátvitel titkosítása és a végponton történő vizsgálat külön kérdés. Egy alkalmazás a titkosítás előtt vagy a feloldás után hozzáférhet a tartalomhoz."],
        ["A készüléken, elküldés előtt végzett ellenőrzés mellett az adatátvitel technikailag titkosított maradhat.", true, "A továbbítási csatorna valóban maradhat titkosított. A magánéleti ígéret mégis változik, mert egy vizsgáló rendszer a lezárás előtt hozzáfér a tartalomhoz."],
        ["A kliensoldali vizsgálat ugyanazt a biztonsági tulajdonságot adja, mint a teljesen vizsgálatlan végpontok közötti titkosítás.", false, "A két rendszer biztonsági kockázatai eltérnek. A beépített vizsgáló képesség új kódot, frissítési csatornát és döntési pontot hoz létre a titkosítás előtt."],
        ["A titkosítás újságírókat, vállalkozásokat, orvosokat és hétköznapi családokat is véd.", true, "A bizalmas kommunikáció nem csak bűnüldözési kérdés. Csalások, adatlopás, ipari kémkedés és személyes megtorlás ellen is védelmet ad."],
        ["Egy csak „jó szereplőknek” használható hátsó kapu biztosan elérhetetlen marad támadók számára.", false, "Egy új hozzáférési út vagy megkerülési képesség támadási felületet teremt. A jogosultság szabályozása csökkentheti a kockázatot, de maga a hozzáférési lehetőség ettől még technikailag létezik."],
        ["A titkosítás védelmének megítéléséhez a jogszöveg mellett a tényleges rendszertervet is vizsgálni kell.", true, "A technikai működés dönti el, ki, mikor és milyen tartalomhoz férhet hozzá. Az általános jogi ígéret csak konkrét, ellenőrizhető garanciákkal értékelhető."],
        ["Ha a szolgáltató nem olvassa el kézzel az üzenetet, a gépi tartalomvizsgálat nem érinti a magánéletet.", false, "A gépi vizsgálat is adatkezelés, és téves jelzés esetén emberi hozzáféréshez vezethet. Emellett maga az automatikus osztályozás is következtetéseket von le a magántartalomból."],
        ["A végpontok védelme azért fontos, mert a támadók gyakran éppen a felhasználó készülékét célozzák.", true, "A biztonság nem csak az adatátvitelen múlik. A készülékre telepített érzékeny ellenőrzési komponens hibája vagy eltérítése széles körű következménnyel járhat."],
        ["A végpontok közötti titkosítás megakadályoz minden digitális bűncselekményt.", false, "A titkosítás a kommunikáció bizalmasságát és sértetlenségét védi, nem old meg minden bűnügyi problémát. Célzott nyomozás, eszközlefoglalás, bejelentés és más módszerek ettől még léteznek."],
      ],
    },
    detection: {
      label: "Felismerési technikák",
      questions: [
        ["Egy pontos kriptográfiai lenyomat azonos bájtsorozatú fájlok összevetésére alkalmas.", true, "A fájl apró módosítása már más pontos lenyomatot adhat. Emiatt az átméretezett vagy átkódolt képek keresésére gyakran más technikát használnak."],
        ["A perceptuális lenyomat csak bitre pontosan azonos fájloknál jelez egyezést.", false, "A perceptuális módszer vizuálisan hasonló változatokat is igyekszik felismerni. Ehhez küszöböt használ, amely téves egyezést is eredményezhet."],
        ["Az új, korábban nem látott képek osztályozásakor a modell pontszámot, megfelelő kalibrálás esetén pedig valószínűségi becslést adhat.", true, "A modell tanult minták alapján ad pontszámot vagy kategóriát; csak megfelelő kalibrálás esetén értelmezhető a pontszám valószínűségként. Ez nem azonos egy szakértő által már azonosított fájl pontos egyezésével."],
        ["A gyermekek szexuális célú behálózása megbízhatóan felismerhető egyetlen tiltott szó listájával.", false, "A behálózás jelentése a kapcsolati helyzettől, a résztvevők életkorától, az előzményektől, a humortól és a manipulációtól függ. Ugyanaz a mondat különböző helyzetben mást jelenthet."],
        ["A beszélgetés értelmezése több magántartalom vizsgálatát igényelheti, mint egy ismert fájl egyezésének ellenőrzése.", true, "A szándék és az összefüggés megértéséhez gyakran üzenetsorozat kell. Ez nagyobb beavatkozást jelenthet a magánéletbe, és több bizonytalansággal járhat."],
        ["A gépi 63%-os modellpontszám vagy valószínűségi becslés azt jelenti, hogy a tartalom jogilag biztosan tiltott.", false, "A pontszám vagy becslés nem jogi ítélet. A kalibrálás, a küszöb, az alaparány, a tanítóadat és az emberi felülvizsgálat mind befolyásolja a jelentését és a következményt."],
        ["Egy felismerő rendszer pontosságát különböző nyelveken és felhasználói csoportokon is mérni kell.", true, "A nyelv, kulturális környezet és életkor változtathatja a modell hibáit. Az összesített pontosság elfedhet egyes csoportokat aránytalanul érintő tévedéseket."],
        ["A nulla téves pozitív eredmény automatikusan azt jelenti, hogy a rendszer minden tiltott tartalmat megtalál.", false, "A rendszer úgy is elérhet nulla téves riasztást, hogy semmit nem jelöl meg. Az érzékenységet és a téves negatív eredményeket is látni kell."],
        ["Az emberi felülvizsgálat csökkentheti, de nem szünteti meg automatikusan a téves jelzés kárát.", true, "A felülvizsgáló is tévedhet, és már a hozzáférés vagy a késedelem is sértheti az érintettet. Fontos a képzés, a korlátozott hozzáférés és a jogorvoslat."],
        ["Minden felismerési feladatnak azonos a hibaaránya és az adatvédelmi kockázata.", false, "A pontos egyezés, a perceptuális hasonlóság, az új kép osztályozása és a beszélgetés értelmezése eltérő feladat. Nem szabad egyetlen pontossági számmal összemosni őket."],
      ],
    },
    math: {
      label: "Hibaarányok és alaparány",
      questions: [
        ["Ha 10 000 üzenetből 10 tiltott és a rendszer 90%-os érzékenységű, akkor várhatóan 9 tiltott üzenetet talál meg.", true, "A tíz tényleges pozitív 90%-a kilenc. A fennmaradó egy téves negatív, vagyis elszalasztott tiltott tartalom."],
        ["A téves pozitív arányt a valóban tiltott üzenetek számából kell kiszámítani.", false, "A téves pozitív arány azt mutatja, az ártatlan esetek mekkora részét jelöli meg hibásan a rendszer. Ezért az alapja a ténylegesen negatív esetek száma."],
        ["0,5%-os téves pozitív aránynál 9 990 ártatlan üzenetből körülbelül 50 téves riasztás lesz.", true, "9 990 × 0,005 = 49,95, amit a szemléltető példában 50-re kerekítünk. A kilenc valódi találattal együtt így 59 riasztás keletkezik."],
        ["Az 59 riasztásból 50 téves esetén a jelzések kevesebb mint fele téves.", false, "50 osztva 59-cel körülbelül 84,7%. A ritka céljelenség miatt még egy látszólag alacsony hibaarány mellett is a riasztások többsége lehet téves."],
        ["A téves negatív eredmény olyan tiltott tartalom, amelyet a rendszer nem jelölt meg.", true, "Ez eltér a téves pozitívtól, amely ártatlan tartalomra adott hibás riasztás. Mindkét hibát külön kell mérni és bemutatni."],
        ["A 99%-os összpontosság önmagában elég a tömeges rendszer hasznosságának megítéléséhez.", false, "Az összpontosság ritka jelenségnél félrevezető lehet. Szükséges az érzékenység, a specificitás, az alaparány és a riasztások pozitív prediktív értéke is."],
        ["Ha csökkentjük a jelzési küszöböt, gyakran több valódi és több téves találat is keletkezik.", true, "A küszöb a téves pozitív és téves negatív hibák közötti kompromisszumot befolyásolja. A pontos hatás a konkrét modell teljesítménygörbéjétől függ."],
        ["A helyesen negatív eset olyan ártatlan üzenet, amelyet a rendszer tévesen megjelölt.", false, "A helyesen negatív esetet a rendszer békén hagyja. A hibásan megjelölt ártatlan üzenet a téves pozitív."],
        ["A ritka esemény alaparánya meghatározza, mennyire értelmezhető egy riasztás.", true, "Ugyanaz a téves pozitív arány más eredményt ad, ha a céljelenség gyakori vagy nagyon ritka. Ez a bázisráta-hatás lényege."],
        ["Ha a téves pozitív arány 0,01%, akkor biztosan nulla ártatlan üzenet kap jelzést tízezer esetből.", false, "9 990 ártatlan üzenet 0,01%-a körülbelül egy. Az egész számú eredmény kerekítéstől és a tényleges mintától függ, de nem garantált a nulla."],
      ],
    },
    rights: {
      label: "Alapjogok és védelem",
      questions: [
        ["Az orvos és a páciens bizalmas kommunikációját is érintheti egy általános tartalomvizsgálat.", true, "Egészségügyi képek és leírások különösen érzékeny adatok. A téves jelzés és az emberi hozzáféréstől való félelem visszatarthat a segítségkéréstől."],
        ["Az ügyvédi titok csak az ügyvédet védi, az ügyfél tisztességes eljáráshoz való jogát nem.", false, "A bizalmas jogi tanácsadás az ügyfél védekezését és a tisztességes eljárást szolgálja. A titok társadalmi és alapjogi funkciót is betölt."],
        ["Az újságírói forrásvédelem sérülése öncenzúrát okozhat.", true, "A források nem adnak át bizonyítékot, ha azonosításuktól vagy megtorlástól tartanak. Ez a nyilvánosságot is megfoszthatja fontos információktól."],
        ["A felnőttek jogszerű intim képei nem kaphatnak téves gépi jelzést.", false, "Az osztályozó vagy hasonlósági rendszer a jogszerű tartalmat is félreértheti. A tévedés itt különösen súlyos méltósági és adatvédelmi kárt okozhat."],
        ["A gyermekek biztonságos segítségkéréséhez is szükség lehet bizalmas csatornára.", true, "Egy fiatal először segítőnek, orvosnak vagy forródrótnak írhat. Ha attól tart, hogy illetéktelenek hozzáférhetnek az üzenetéhez, később vagy egyáltalán nem kér segítséget."],
        ["A magánélethez való jog kizárja a célzott, bírói engedéllyel végzett nyomozást.", false, "Az alapjogok korlátozhatók legitim célból, ha a beavatkozás jogszerű, szükséges és arányos. A célzott eljárás és az általános vizsgálat között fontos különbség van."],
        ["A gyors értesítés és jogorvoslat csökkentheti egy téves riasztás kárát.", true, "Az érintettnek tudnia kell, mi történt, és érdemben vitathatnia kell a döntést. Bizonyos nyomozási szakaszban az értesítés halasztható lehet, de nem tűnhet el korlátlanul."],
        ["A tüntetésszervezők kapcsolati hálójának feltárása nem érinti a politikai részvételt.", false, "A megfigyeléstől való félelem elrettenthet a békés szerveződéstől. Ez a magánélet mellett a gyülekezési és véleménynyilvánítási szabadságot is érintheti."],
        ["Az adatminimalizálás azt jelenti, hogy csak a célhoz szükséges adatot kezelik.", true, "A célhoz nem szükséges tartalmat nem kell gyűjteni vagy továbbítani. Az, hogy az adatot meddig tarthatják meg, külön elv: ez a korlátozott tárolhatóság."],
        ["Ha a cél gyermekvédelem, arányossági vizsgálatra nincs szükség.", false, "A cél kiemelkedően fontos, de a választott eszköznek akkor is szükségesnek és arányosnak kell lennie. A jogállami vizsgálat éppen a súlyos céloknál is elengedhetetlen."],
      ],
    },
    abuse: {
      label: "Politikai visszaélés",
      questions: [
        ["Egy tartalomkereső képesség későbbi célkiterjesztésének kockázatát már a tervezéskor vizsgálni kell.", true, "A rendszer képessége túlélheti a jelenlegi politikai szándékot. A garanciákat ezért úgy kell kialakítani, hogy a későbbi rosszhiszemű használatnak is ellenálljanak."],
        ["A politikai visszaélés kockázatának említése azt állítja, hogy a jelenlegi döntéshozók biztosan visszaélnek a rendszerrel.", false, "A kockázatelemzés nem jóslat és nem személyes vád. Azt vizsgálja, milyen visszaélési lehetőségeket teremt a rendszer, és milyen garanciák előzhetik meg ezeket."],
        ["A keresési lista frissítésének ellenőrizhetősége fontos visszaélés elleni garancia.", true, "Ha nem látható, ki és milyen jogalapon változtatja a célokat, a rendszer más tartalomra is átállítható. A manipulációt jelző napló és független engedély csökkenti ezt a kockázatot."],
        ["Az automatikus jelzésnek minden esetben elegendőnek kell lennie házkutatáshoz vagy fióktiltáshoz.", false, "A gépi rendszer tévedhet vagy manipulálható. Súlyos intézkedéshez független ellenőrzés, megfelelő bizonyíték és arányos jogi eljárás szükséges."],
        ["A hatósági döntési lánc szelektív működése politikailag elfogult eredményhez vezethet az azonos gépi jelzések kezelésében.", true, "Nemcsak az algoritmus lehet elfogult: a továbbítás, a fontossági sorrend és a nyomozás emberi döntései is. Összehasonlítható naplók és külső felügyelet segíthetnek ezt kimutatni."],
        ["A Pegasus-ügy bizonyítja, hogy a Chat Control javaslatát már politikai ellenfelek ellen használták.", false, "A két rendszer nem azonos, ezért ilyen közvetlen állítás nem lenne pontos. A Pegasus-ügy arra szolgálhat bizonyítékként, hogy megfigyelési jogosultságokkal Európában is visszaéltek."],
        ["Az intim adatok kiszivárgása politikai lejáratásra is alkalmas lehet.", true, "Kiragadott magánbeszélgetés vagy kép akkor is kárt okozhat, ha nincs köze bűncselekményhez. A hozzáférés korlátozása és a naplózás ezért demokratikus garancia is."],
        ["A független bírói engedély szükségtelenné tesz minden technikai auditot.", false, "A bíró jogi szükségességet és arányosságot vizsgálhat, de a rendszer technikai hibáit külön szakértelem tárja fel. A két garancia kiegészíti, nem helyettesíti egymást."],
        ["A személyazonosságot fel nem fedő életkor-igazolás csökkentheti a politikai profilalkotás kockázatát.", true, "A magánszférát védő igazolás csak azt bizonyíthatja, hogy a korhatár teljesül. Nem szükséges hozzá tartós név-, okmány- vagy biometrikus adatbázist kapcsolni minden kommunikációs fiókhoz."],
        ["Ha egy rendszer ma jó célt szolgál, a későbbi keresési célok jogi korlátozása felesleges.", false, "A demokratikus intézményeket nem csak jóhiszemű használatra tervezik. A célhoz kötöttségnek, az engedélyezésnek és az ellenőrzésnek a későbbi kiterjesztést is akadályoznia kell."],
      ],
    },
    votes: {
      label: "Szavazások és cselekvés",
      questions: [
        ["2026. július 9-én 314 képviselő a Tanács szövegének elutasítása mellett szavazott.", true, "Ebben a konkrét szavazásban az igen az elutasítást jelentette. Ezért a 314-et nem szabad automatikusan a Chat Control támogatásaként értelmezni."],
        ["A 2026. július 9-i 276 szavazat a Tanács szövegének elutasítását támogatta.", false, "A 276 szavazat az elutasítási indítvány ellen érkezett. Az egyes szavazásoknál mindig el kell olvasni, pontosan mire vonatkozott az igen és a nem."],
        ["A Tanács szövegének elutasításához legalább 360 igen kellett volna.", true, "A második olvasatban az összes hivatalban lévő képviselő abszolút többsége volt szükséges. A 314 igen ezért 46 szavazattal elmaradt a küszöbtől."],
        ["A 314 több volt a 276-nál, ezért az elutasítási indítvány jogilag elfogadottnak számított.", false, "Nem a leadott igen és nem szavazatok egyszerű aránya döntött. Az abszolút többségi küszöböt kellett elérni, ami nem sikerült."],
        ["A 2023-as LIBE-szavazás eredménye 51 igen, 2 nem és 1 tartózkodás volt.", true, "Ez a módosított bizottsági jelentésről szóló szakbizottsági döntés volt. Nem szabad teljes parlamenti végszavazásként bemutatni."],
        ["A 2024-es 469–112–37 eredmény a 2.0 végleges elfogadásáról szólt.", false, "Ez az ideiglenes 1.0 kivétel első meghosszabbításának parlamenti szavazása volt. A tartós 2.0 javaslat ettől külön eljárás."],
        ["A képviselők név szerinti szavazatait hivatalos európai parlamenti jegyzőkönyvek rögzítik.", true, "A jegyzőkönyvek álláspontonként felsorolják a neveket. A frakció szerinti összesítés hasznos, de az egyéni szavazatot nem helyettesíti."],
        ["Minden szavazásban az „igen” a megfigyelési rendszer támogatását jelenti.", false, "Az igen mindig a feltett kérdés támogatása. Elutasítási indítványnál például éppen a szöveggel szembeni fellépést jelentheti."],
        ["Egy döntéshozónak írt pontos levél kérhet célzott vizsgálatot, bírói engedélyt, a titkosítás védelmét és független műszaki ellenőrzést egyszerre.", true, "A gyermekvédelem támogatása nem zárja ki az erős alapjogi garanciák követelését. A konkrét kérések könnyebben számonkérhetők, mint az általános jelszavak."],
        ["A téves állítások továbbosztása erősíti a hiteles szakpolitikai kritikát.", false, "A könnyen cáfolható túlzás eltereli a figyelmet a valós kockázatokról. A dátum, jogi állapot, technikai képesség és szavazási kérdés pontos megnevezése meggyőzőbb."],
      ],
    },
  };

  window.CHAT_CONTROL_QUIZ = Object.entries(categories).flatMap(([category, group]) =>
    group.questions.map(([statement, answer, detail], index) => ({
      id: `${category}-${String(index + 1).padStart(2, "0")}`,
      category,
      categoryLabel: group.label,
      statement,
      answer,
      detail,
    })),
  );
})();
